
// Actions types for PRODUCTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const PRODUCTS_IS_LOADING = 'PRODUCTS_IS_LOADING';
export const PRODUCTS_HAS_ERRORED = 'PRODUCTS_HAS_ERRORED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ASSIGN_PRODUCTS = 'ASSIGN_PRODUCTS';
export const CANCEL_PRODUCTS = 'CANCEL_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';


// Actions types for categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORIES_IS_LOADING = 'CATEGORIES_IS_LOADING';
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';


// Actions for modal
export const MODAL_HAS_CHANGED = 'MODAL_HAS_CHANGED';

