
// Actions types for PRODUCTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const PRODUCTS_IS_LOADING = 'PRODUCTS_IS_LOADING';
export const PRODUCTS_HAS_ERRORED = 'PRODUCTS_HAS_ERRORED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ASSIGN_PRODUCTS = 'ASSIGN_PRODUCTS';
export const CANCEL_PRODUCTS = 'CANCEL_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';


// Actions types for positions
export const GET_POSITIONS = 'GET_POSITIONS_SUCCESS';
export const POSITIONS_IS_LOADING = 'POSITIONS_IS_LOADING';
export const POSITIONS_HAS_ERRORED = 'POSITIONS_HAS_ERRORED';

// Actions for employees
export const GET_EMPLOYEES_FOR_AUTOCOMPLETE_SUCCESS = 'GET_EMPLOYEES_FOR_AUTOCOMPLETE_SUCCESS';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const EMPLOYEES_IS_LOADING = 'EMPLOYEES_IS_LOADING';
export const EMPLOYEES_HAS_ERRORED = 'EMPLOYEES_HAS_ERRORED';

// Actions for modal
export const MODAL_HAS_CHANGED = 'MODAL_HAS_CHANGED';

// Actions for organizations
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const ORGANIZATIONS_IS_LOADING = 'ORGANIZATIONS_IS_LOADING';
export const ORGANIZATIONS_HAS_ERRORED = 'ORGANIZATIONS_HAS_ERRORED';
export const EDIT_ORGANIZATION = 'EDIT_ORGANIZATION';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';

// Actions for catering
export const GET_CATERING = 'GET_CATERING';
export const CATERING_IS_LOADING = 'CATERING_IS_LOADING';
export const CATERING_HAS_ERRORED = 'CATERING_HAS_ERRORED';

// Actions for authorization
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";